### ISSUE TITLE
[BUG] Some crash

### ISSUE THREAD

**Issue by DeathNorn** [PoloNX/SimpleModDownloader#58]
**Describe the bug**
Whenever I try to install any mod it crashes the app I believe it is because of the image loading in as soon as you click on the mod.  It didn’t do this for the earlier version since you could choose to load the images.

**On which mod**
All of them mod whenever it fells like it.

**Log file**
Paste the log file here (you can find it at /config/SimpleModDownloader/log.log)
Don't launch the app again before pasting the log file, it will be overwritten

18:43:24.104[0;34m[INFO][0m switch system theme: Dark
18:43:24.105[0;34m[INFO][0m Using platform Switch
18:43:24.172[0;34m[INFO][0m glfw: GL Vendor: nouveau
18:43:24.172[0;34m[INFO][0m glfw: GL Renderer: NV120
18:43:24.172[0;34m[INFO][0m glfw: GL Version: 4.3 (Core Profile) Mesa 20.1.0-rc3
18:43:24.172[0;34m[INFO][0m glfw: GLFW Version: 3.3.4
18:43:24.220[0;34m[INFO][0m glfw: Monitor: Default
18:43:24.221[0;32m[DEBUG][0m Vibration clear #0
18:43:24.221[0;32m[DEBUG][0m Vibration clear #1
18:43:24.221[0;32m[DEBUG][0m Vibration clear #2
18:43:24.221[0;32m[DEBUG][0m Vibration clear #3
18:43:24.221[0;32m[DEBUG][0m Vibration clear #4
18:43:24.221[0;34m[INFO][0m switch system locale: en-US
18:43:24.221[0;33m[WARNING][0m Cannot find custom font, (Searched at: romfs:/font/font.ttf)
18:43:24.225[0;32m[DEBUG][0m Adding an inputs block token (tokens=1)
18:43:24.574[0;32m[DEBUG][0m 49 games found
18:43:24.577[0;32m[DEBUG][0m Cell #0 - added
18:43:24.599[0;32m[DEBUG][0m Cell #1 - added
18:43:24.615[0;32m[DEBUG][0m Cell #2 - added
18:43:24.646[0;32m[DEBUG][0m Cell #3 - added
18:43:24.666[0;32m[DEBUG][0m Cell #4 - added
18:43:24.689[0;32m[DEBUG][0m Cell #5 - added
18:43:24.689[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:24.692[0;32m[DEBUG][0m Hiding brls::AppletFrame (id="applet")
18:43:24.692[0;32m[DEBUG][0m push activity to the stack
18:43:24.692[0;32m[DEBUG][0m Showing brls::AppletFrame (id="applet")
18:43:24.692[0;34m[INFO][0m AppletFocusState_InFocus
18:43:24.806[0;34m[INFO][0m Window size changed to 1280x720, content size: 1280x720 factor: 1
18:43:24.806[0;34m[INFO][0m scale factor: 1
18:43:24.926[0;32m[DEBUG][0m Removing an inputs block token (tokens=0)
18:43:25.679[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:26.629[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:27.095[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:27.696[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:28.206[0;32m[DEBUG][0m Giving focus to brls::SelectorCell (id="language_selector")
18:43:28.556[0;32m[DEBUG][0m Giving focus to brls::BooleanCell (id="debug_cell")
18:43:29.074[0;34m[INFO][0m Open the debug layer
18:43:30.874[0;34m[INFO][0m Close the debug layer
18:43:31.556[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:31.928[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:32.579[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:32.985[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:36.479[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:36.795[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:37.633[0;32m[DEBUG][0m 49 games found
18:43:37.636[0;32m[DEBUG][0m Cell #0 - added
18:43:37.659[0;32m[DEBUG][0m Cell #1 - added
18:43:37.677[0;32m[DEBUG][0m Cell #2 - added
18:43:37.703[0;32m[DEBUG][0m Cell #3 - added
18:43:37.725[0;32m[DEBUG][0m Cell #4 - added
18:43:37.749[0;32m[DEBUG][0m Cell #5 - added
18:43:37.749[0;32m[DEBUG][0m Giving focus to brls::SidebarItem
18:43:38.490[0;32m[DEBUG][0m Giving focus to GameCell
18:43:38.840[0;32m[DEBUG][0m Giving focus to GameCell
18:43:39.107[0;32m[DEBUG][0m Giving focus to GameCell
18:43:39.172[0;32m[DEBUG][0m Cell #0 - destroyed
18:43:39.390[0;32m[DEBUG][0m Giving focus to GameCell
18:43:39.462[0;32m[DEBUG][0m Cell #6 - added
18:43:39.489[0;32m[DEBUG][0m Cell #1 - destroyed
18:43:41.040[0;32m[DEBUG][0m Giving focus to GameCell
18:43:41.111[0;32m[DEBUG][0m Cell #7 - added
18:43:41.139[0;32m[DEBUG][0m Cell #2 - destroyed
18:43:41.723[0;32m[DEBUG][0m Giving focus to GameCell
18:43:41.792[0;32m[DEBUG][0m Cell #8 - added
18:43:41.822[0;32m[DEBUG][0m Cell #3 - destroyed
18:43:42.257[0;32m[DEBUG][0m Giving focus to GameCell
18:43:42.325[0;32m[DEBUG][0m Cell #9 - added
18:43:42.355[0;32m[DEBUG][0m Cell #4 - destroyed
18:43:43.073[0;32m[DEBUG][0m Requesting: https://gamebanana.com/apiv11/Util/Game/NameMatch?_sName=DRAGON%20BALL%20FighterZ
18:43:43.267[0;32m[DEBUG][0m Requesting: https://gamebanana.com/apiv11/Game/6246/Subfeed?_nPage=1?_nPerpage=50&_csvModelInclusions=Mod
18:43:43.429[0;32m[DEBUG][0m Downloading image: https://images.gamebanana.com/img/banners/games/6270052034aa6.jpg
18:43:43.535[0;32m[DEBUG][0m 15 mods found
18:43:43.538[0;32m[DEBUG][0m Cell #0 - added
18:43:43.541[0;32m[DEBUG][0m Mod name : Copy Vegeta
18:43:43.542[0;32m[DEBUG][0m Cell #1 - added
18:43:43.544[0;32m[DEBUG][0m Mod name : Magician's Red
18:43:43.545[0;32m[DEBUG][0m Cell #2 - added
18:43:43.547[0;32m[DEBUG][0m Mod name : Orlando Perfect Cell
18:43:43.547[0;32m[DEBUG][0m Cell #3 - added
18:43:43.550[0;32m[DEBUG][0m Mod name : Sonic Adventure Music Pack
18:43:43.550[0;32m[DEBUG][0m Cell #4 - added
18:43:43.552[0;32m[DEBUG][0m Mod name : DazzArts SSJ4 Gogeta Recolor
18:43:43.553[0;32m[DEBUG][0m Cell #5 - added
18:43:43.555[0;32m[DEBUG][0m Mod name : Thank You Toriyama.
18:43:43.556[0;32m[DEBUG][0m Cell #6 - added
18:43:43.556[0;32m[DEBUG][0m Giving focus to ModCell
18:43:44.206[0;32m[DEBUG][0m Giving focus to ModCell
18:43:44.873[0;32m[DEBUG][0m Giving focus to ModCell
18:43:45.173[0;32m[DEBUG][0m Giving focus to ModCell
18:43:45.205[0;32m[DEBUG][0m Cell #0 - destroyed
18:43:45.308[0;32m[DEBUG][0m Mod name : Smooth Cell
18:43:45.309[0;32m[DEBUG][0m Cell #7 - added
18:43:45.423[0;32m[DEBUG][0m Giving focus to ModCell
18:43:45.455[0;32m[DEBUG][0m Cell #1 - destroyed
18:43:45.555[0;32m[DEBUG][0m Mod name : Ultimate Dragon Ball FighterZ Mod - Season 2 v2.01
18:43:45.556[0;32m[DEBUG][0m Cell #8 - added
18:43:45.690[0;32m[DEBUG][0m Giving focus to ModCell
18:43:45.722[0;32m[DEBUG][0m Cell #2 - destroyed
18:43:45.822[0;32m[DEBUG][0m Mod name : Frieza with 2 guns
18:43:45.823[0;32m[DEBUG][0m Cell #9 - added
18:43:46.373[0;32m[DEBUG][0m Giving focus to ModCell
18:43:46.405[0;32m[DEBUG][0m Cell #3 - destroyed
18:43:46.505[0;32m[DEBUG][0m Mod name : Kokonoe Labcoat 21 (Color 02-12)
18:43:46.506[0;32m[DEBUG][0m Cell #10 - added
18:43:46.723[0;32m[DEBUG][0m Giving focus to ModCell
18:43:46.755[0;32m[DEBUG][0m Cell #4 - destroyed
18:43:46.855[0;32m[DEBUG][0m Mod name : Original Gogeta on Color03-04 wo shader
18:43:46.856[0;32m[DEBUG][0m Cell #11 - added
18:43:46.973[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.005[0;32m[DEBUG][0m Cell #5 - destroyed
18:43:47.073[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.089[0;32m[DEBUG][0m Mod name : Goku from Fortnite
18:43:47.089[0;32m[DEBUG][0m Cell #12 - added
18:43:47.122[0;32m[DEBUG][0m Cell #6 - destroyed
18:43:47.173[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.189[0;32m[DEBUG][0m Mod name : Infinite Azure
18:43:47.189[0;32m[DEBUG][0m Cell #13 - added
18:43:47.239[0;32m[DEBUG][0m Cell #7 - destroyed
18:43:47.290[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.305[0;32m[DEBUG][0m Mod name : Majin Janemba (Dragon Ball Heroes)
18:43:47.306[0;32m[DEBUG][0m Cell #14 - added
18:43:47.339[0;32m[DEBUG][0m Cell #8 - destroyed
18:43:47.439[0;32m[DEBUG][0m Mod name : BLM Beast Gohan
18:43:47.439[0;32m[DEBUG][0m Cell #15 - added
18:43:47.623[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.655[0;32m[DEBUG][0m Cell #9 - destroyed
18:43:47.873[0;32m[DEBUG][0m Giving focus to ModCell
18:43:47.990[0;32m[DEBUG][0m Giving focus to ModCell
18:43:50.323[0;32m[DEBUG][0m Search button pressed
18:43:57.986[0;32m[DEBUG][0m Requesting: https://gamebanana.com/apiv11/Game/6246/Subfeed?_nPage=1&_nPerpage=50&_sName=nude&_csvModelInclusions=Mod
18:43:58.198[0;32m[DEBUG][0m Cell #0 - added
18:43:58.198[0;32m[DEBUG][0m Mod name : Nude Android 21 (Lab Coat)
18:43:58.198[0;32m[DEBUG][0m Cell #1 - added
18:43:58.198[0;32m[DEBUG][0m Mod name : Nude Videl Edits
18:43:58.199[0;32m[DEBUG][0m Cell #2 - added
18:43:58.199[0;32m[DEBUG][0m Mod name : Nude Android 21 (Majin)
18:43:58.199[0;32m[DEBUG][0m Cell #3 - added
18:43:58.229[0;34m[INFO][0m AppletFocusState_InFocus
18:43:59.856[0;32m[DEBUG][0m Giving focus to ModCell
18:44:00.656[0;32m[DEBUG][0m Giving focus to ModCell
18:44:01.790[0;32m[DEBUG][0m Giving focus to ModCell
18:44:02.390[0;32m[DEBUG][0m Giving focus to ModCell
18:44:03.890[0;32m[DEBUG][0m Giving focus to ModCell
18:44:04.256[0;32m[DEBUG][0m Giving focus to ModCell
18:44:04.723[0;32m[DEBUG][0m Giving focus to ModCell
18:44:05.056[0;32m[DEBUG][0m Giving focus to ModCell
18:44:05.873[0;32m[DEBUG][0m Mod name : Nude Android 21 (Lab Coat)
18:44:05.873[0;32m[DEBUG][0m Requesting: https://gamebanana.com/apiv11/Mod/487651?_csvProperties=_sText,_aFiles,_aPreviewMedia
18:44:06.012[0;32m[DEBUG][0m Giving focus to brls::ScrollingFrame (id="mod_preview_scrolling")
18:44:06.089[0;32m[DEBUG][0m Giving focus to brls::Button (id="download")
18:44:06.090[0;32m[DEBUG][0m Downloading image: https://images.gamebanana.com/img/ss/mods/65923b5f490ea.jpg
18:44:06.105[0;32m[DEBUG][0m Giving focus to brls::ScrollingFrame (id="mod_preview_scrolling")
18:44:06.221[0;32m[DEBUG][0m Downloading image: https://images.gamebanana.com/img/ss/mods/65923b6208b1e.jpg
18:44:06.376[0;32m[DEBUG][0m Download

**To Reproduce**
1. Go to any mod with alot of high quality images
2. Click on the mod in the list for a game with a large mod fanbase.

**Expected behavior**
Page loads perfectly and you can download the mods inside

**Screenshots**

**Switch:**
 - Horizon Os version (17.0.1)
 - SimpleModDownloader version (2.0.0)

**Additional context**
It’s literally only on the 2.0.0 version of this and it wont download mods properly if its not the latest one

**Comment by DeathNorn** [comment]
Also it does it on the dragon ball z fighters section of mods alot for example the pic below “excuse the broken screen protector”.
![image](https://github.com/PoloNX/SimpleModDownloader/assets/75560758/8d4ecc80-b983-4b67-9f6b-bc063b1bf9b5)
![image](https://github.com/PoloNX/SimpleModDownloader/assets/75560758/83a94338-0c46-47d1-bffb-b709399a3da4)

**Comment by PoloNX** [comment]
does it do the same thing for all games ?

**Comment by PoloNX** [comment]
Maybe it's a problem with ssl certificate. your console time is synced ? you can sync it with https://github.com/nedex/QuickNTP

**Comment by PoloNX** [comment]
I can see what you searched with your logs ( ͡° ͜ʖ ͡° )

**Comment by DeathNorn** [comment]
Yah dont worry about the searches ahaha ill sync the certificate

**Comment by DeathNorn** [comment]
Your app is very usefull for an otherwise annoying modding scene for setup

**Comment by DeathNorn** [comment]
Also what server should it be synced to

**Comment by DeathNorn** [comment]
Also i synced it with main and it crashes less but some mods when loaded do crashes still

**Comment by DeathNorn** [comment]
Maybe im missing something else

**Comment by FlameSlap** [comment]
I'm having the sane exact issue. Nothing downloads. Everything crashes. My time is synced as well.

**Comment by FlameSlap** [comment]
> Also i synced it with main and it crashes less but some mods when loaded do crashes still

Are you able to click the download button?

**Comment by PoloNX** [comment]
> Also i synced it with main and it crashes less but some mods when loaded do crashes still

Which mod ? Hour should be sync to improve the security with ssl certificates. Without them, someone can edit informations you receive.

**Comment by PoloNX** [comment]
> I'm having the same exact issue. Nothing downloads. Everything crashes. My time is synced as well.
> 
> Edit: I resynced it with QuickNTP cloudflare and it loads the mod now but the download button doesnt click. In other words it wont even initiate the download.

It's because the mod doesn't contain romfs folder so is incompatible with the app

**Comment by FlameSlap** [comment]
> > I'm having the same exact issue. Nothing downloads. Everything crashes. My time is synced as well.
> > 
> > Edit: I resynced it with QuickNTP cloudflare and it loads the mod now but the download button doesnt click. In other words it wont even initiate the download.
> 
> It's because the mod doesn't contain romfs folder so is incompatible with the app

![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/db5beace-fef0-46fb-abcb-701d4f80c3e8)

The download button in your app does not work for any mod. The one in the picture.

**Comment by PoloNX** [comment]
I made a fix for ssbu. Download the latest version in the Actions tab of the github

**Comment by FlameSlap** [comment]
> I made a fix for ssbu. Download the latest version in the Actions tab of the github

I don't understand how to get a precompiled copy from here.

![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/5895d9e2-17ec-4687-97db-ea87ebc2d642)

![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/19d1217e-7b73-422f-8701-ad49a2cb69a2)

I don't have a work environment to compile it in.

**Comment by PoloNX** [comment]
My bad I didn't upload assets in the workflow. I'm not on my computer so I can't edit it. I'll send you a build soon

**Comment by PoloNX** [comment]
Juste edited from my phone. You should find a build here when it's finished https://github.com/PoloNX/SimpleModDownloader/actions/runs/8471358046

**Comment by FlameSlap** [comment]
> Juste edited from my phone. You should find a build here when it's finished https://github.com/PoloNX/SimpleModDownloader/actions/runs/8471358046

Got it testing now. 👍🏻

**Comment by FlameSlap** [comment]
Dang... after It downloaded and I backed out of the app by pressing the B button it crashed. I think the mod downloaded fine though. Let me have a look and see.

![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/87318d9f-f365-46c4-8227-01395ba89a24)

**Comment by DeathNorn** [comment]
Wow i didn’t expect such a great action taken im taken aback by the creators supportiveness for his users. Ill be keeping and eye out for this guy and also telling everyone about how great he is.

**Comment by DeathNorn** [comment]
Edit it crashes more now sadly

**Comment by DeathNorn** [comment]
Basically unusable

**Comment by DeathNorn** [comment]
Tried it on minecraft mods as well

**Comment by FlameSlap** [comment]
> Tried it on minecraft mods as well

You need to give more detail if you want to try and see if the developer can fix it. Pictures help too sometimes.

**Comment by PoloNX** [comment]
> Dang... after the mod downloaded and I backed out of the app by pressing the B button it crashed. I think the mod downloaded fine though. Let me have a look and see.
> 
> ![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/87318d9f-f365-46c4-8227-01395ba89a24)
> 
> Edit: I tried it again with a second SSBU mod and the same thing happened. After I download the mod and back out with B, it crashes.
> 
> Edit 2: bartman and el chavo mods both downloaded and installed fine though.
> 
> ![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/b42e701c-c9ef-4a7e-8bb5-a314342e8b94)

Fixed one bug and a new one appear, this week end I'll have some times to fix everything

**Comment by PoloNX** [comment]
Hey @FlameSlap @DeathNorn I fixed a lot of bugs. The error when you press "B" was introduced in a new commit of borealis which was a breaking change and I completly forgot about it. Can you try the last build here ? Normally there's a message when a mod isn't supported or when you search a mod with a string lower than 3 characters 
https://github.com/PoloNX/SimpleModDownloader/actions/runs/8489971503

**Comment by PoloNX** [comment]
Now it's not necessary to sync the time

**Comment by PoloNX** [comment]
https://github.com/PoloNX/SimpleModDownloader/assets/57038157/e9db5b95-66c2-44f7-af0a-9bfc501eb461

**Comment by FlameSlap** [comment]
> https://github.com/PoloNX/SimpleModDownloader/assets/57038157/e9db5b95-66c2-44f7-af0a-9bfc501eb461
> 
> 
> 
> 

Is this updated version already in the release tab?

**Comment by PoloNX** [comment]
Lmao copy past moment

**Comment by PoloNX** [comment]
Fixed

**Comment by FlameSlap** [comment]
> Fixed 

Just a side note. The latest upcomingswitchgames artifact still crashes/freezes after backing out pressing the B button.

![image](https://github.com/PoloNX/SimpleModDownloader/assets/79780392/b2fb9c3a-ef5c-406b-acd3-8cdabe966d6b)

**Comment by PoloNX** [comment]
You're talking of SimpleModDownloader or UpcomingSwitchGames ?

**Comment by FlameSlap** [comment]
> You're talking of SimpleModDownloader or UpcomingSwitchGames ?

This error is from Upcomingswitchgames because that is what the artifact had before you fixed it. I tested it and Just wanted to let you know.

**Comment by PoloNX** [comment]
Oh okay. I know this issue I should fix it

**Comment by FlameSlap** [comment]
> Oh okay. I know this issue I should fix it 

I tested simplemodmanager now and it ran smoothly! 👏🏻🤙🏻🙌🏻 No crashes or freezes and I was able to back out with no problems so far. I was also able to download a mod with zero issues. 👍🏻

**Comment by FlameSlap** [comment]
> Basically unusable 
Patients young grasshopper. He is working very hard on his apps and they are working much MUCH better now.  🙌🏻👏🏻👍🏻🤜🏻🤛🏻

**Comment by PoloNX** [comment]
Ahah thanks. Can I close the issue or you have another thing to notice ?

**Comment by FlameSlap** [comment]
> Ahah thanks. Can I close the issue or you have another thing to notice ?

I think it's fine to close it now. The app is downloading mods that are compatible and is no longer crashing.
